describe('test flow', () => {
  it('flow 1', () => {
    cy.visit('http://localhost:3000/')
    cy.get('[id="username"]').type('Heath93')
    cy.get('[id="password"]').type('s3cret')
    cy.get('[class=PrivateSwitchBase-input-14]').check()
    cy.get('[data-test="signin-submit"]').click()
    cy.get('[data-test="sidenav-signout"]').contains('Logout').should('exist')

    cy.get('[data-test="sidenav-home"]').click()
    cy.contains('Everyone').should('be.visible')
    cy.get('[data-test="nav-top-new-transaction"]').click()
    cy.get('[data-test="user-list-search-input"]').should('exist')
    cy.get('[data-test="users-list"] li:first').click()
    cy.get('[data-test="transaction-create-amount-input"]').should('exist')
    cy.get('[id="transaction-create-description-input"]').click()
    cy.contains('Please enter a valid amount').should('be.visible')
    cy.get('[id="amount"]').click()
    cy.contains('Please enter a note').should('be.visible')
    cy.get('[data-test="transaction-create-amount-input"]').type('100')
    cy.get('[data-test="transaction-create-description-input"]').type('s3cret')
    cy.get('[data-test="transaction-create-submit-payment"]').click()
    cy.get('[data-test="new-transaction-create-another-transaction"]').should('exist')
    cy.contains('$1,409.53').should('be.visible')
    cy.get('[data-test="new-transaction-create-another-transaction"]').click()
    cy.get('[data-test="users-list"] li:first').click()
    cy.get('[data-test="transaction-create-amount-input"]').type('-100')
    cy.get('[data-test="transaction-create-description-input"]').type('s3cret')
    cy.get('[data-test="transaction-create-submit-payment"]').click()
    cy.get('[data-test="new-transaction-create-another-transaction"]').should('exist')
    cy.contains('$1,509.53').should('be.visible')

    cy.get('[data-test="sidenav-user-settings"]').click()
    cy.contains('User Settings').should('be.visible')
    cy.get('[data-test="user-settings-firstName-input"]').clear().type('My_new_name')
    cy.get('[data-test="user-settings-submit"]').click()
    cy.contains('My_new_name').should('be.visible')
    cy.get('[data-test="user-settings-firstName-input"]').clear().type('My_old_name')
    cy.get('[data-test="user-settings-submit"]').click()

    cy.get('[data-test="sidenav-bankaccounts"]').click()
    cy.get('[data-test="bankaccount-new"]').should('exist')
    cy.get('[data-test="bankaccount-new"]').click()
    cy.contains('Create Bank Account').should('be.visible')
    cy.get('[id="bankaccount-bankName-input"]').click()
    cy.get('[id="bankaccount-routingNumber-input"]').click()
    cy.get('[id="bankaccount-accountNumber-input"]').click()
    cy.get('[id="bankaccount-bankName-input"]').click()
    cy.contains('Enter a bank name').should('be.visible')
    cy.contains('Enter a valid bank routing number').should('be.visible')
    cy.contains('Enter a valid bank account number').should('be.visible')
    cy.get('[id="bankaccount-bankName-input"]').type('aaaaa')
    cy.get('[id="bankaccount-routingNumber-input"]').type('000000000')
    cy.get('[id="bankaccount-accountNumber-input"]').type('000000000')
    cy.get('[data-test="bankaccount-submit"]').click()
    cy.contains('aaaaa').should('be.visible')
    cy.get('[data-test="bankaccount-list"]')
      .children('li') // Select all child list items (bank accounts)
      .last() // Get the last child (bottom element)
      .find('[data-test="bankaccount-delete"]') // Find the delete button within the last list item
      .click(); // Click the delete button
    // cy.contains('aaaaa (Deleted)').should('not.be.visible');
    
    cy.get('[data-test="sidenav-signout"]').click()
    cy.get('[class="MuiTypography-root MuiTypography-h5"]').contains('Sign in').should('exist')
  })
})